clusterName: logs

security:
  enabled: true
  name: logging
  password: qwerty

ports:
  http: 9200
  communication: 9300

resources:
  requests:
    cpu: 200m
    memory: 1024Mi
  limits:
    cpu: 200m
    memory: 1024Mi
