---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-monitor
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres-exporter
  namespaceSelector:
    matchNames: [ default ]
  endpoints:
    - port: http
      interval: 5s
