---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: java-service-monitor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: java-service
  endpoints:
    - port: java-service
