apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-pipeline-configmap
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-pipeline-configmap
data:
  pipeline.conf: |-
    input {
      tcp {
        port => 4560
        codec => json_lines
      }
    }
    filter {
      grok {
        match => { "message" => "%{TIMESTAMP_ISO8601:timestamp}\s+%{LOGLEVEL:severity}\s+\[%{DATA:service},%{DATA:trace},%{DATA:span}\]\s+%{DATA:pid}\s+---\s+\[%{DATA:thread}\]\s+%{DATA:class}\s+:\s+%{GREEDYDATA:rest}" }
      }
      date {
        match => ["timestamp", "ISO8601"]
      }
    }
    output {
      elasticsearch {
        hosts => "elasticsearch-service:9200"
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config-configmap
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-config-configmap
data:
  logstash.yml: |-
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline