apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-deployment
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/component: logging
    app.kubernetes.io/part-of: micro-services
    app.kubernetes.io/managed-by: helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      name: {{ .Chart.Name }}
      labels:
        app: {{ .Chart.Name }}
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/version: "{{ .Chart.Version }}"
        app.kubernetes.io/component: logging
        app.kubernetes.io/part-of: micro-services
        app.kubernetes.io/managed-by: helm
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: {{ .Chart.Name }}
          image: "docker.elastic.co/logstash/logstash:{{ .Values.version }}"
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          volumeMounts:
            - name: {{ .Chart.Name }}-config-volume
              mountPath: /usr/share/logstash/config
            - name: {{ .Chart.Name }}-pipeline-volume
              mountPath: /usr/share/logstash/pipeline
          ports:
            - name: {{ .Chart.Name }}
              containerPort: {{ .Values.port }}
      volumes:
        - name: {{ .Chart.Name }}-config-volume
          configMap:
            name: {{ .Chart.Name }}-config-configmap
        - name: {{ .Chart.Name }}-pipeline-volume
          configMap:
            name: {{ .Chart.Name }}-pipeline-configmap