apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-configmap
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/component: elasticsearch
    app.kubernetes.io/part-of: micro-services
    app.kubernetes.io/managed-by: helm
data:
  users_roles: |-
    kibana_admin:{{ .Values.username }}
    logstash_admin:{{ .Values.username }}
    superuser:{{ .Values.username }}
  users: |-
    {{ .Values.username }}:$2a$10$rJB8uIS8lQL0z1QCDNUDyeqCCl3Ir2zmhvoeFeJvOXeIR0SEgi7Gy