kind: Service
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-service
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-service
spec:
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
  clusterIP: None
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.ports.http }}
      targetPort: {{ .Values.ports.http }}
    - name: communication
      protocol: TCP
      port: {{ .Values.ports.communication }}
      targetPort: {{ .Values.ports.communication }}