kind: Service
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-service
  namespace: kube-system
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-service
    app.kubernetes.io/version: "{{ .Values.version }}"
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: micro-services
    app.kubernetes.io/managed-by: helm
spec:
  selector:
    app: {{ .Chart.Name }}
  clusterIP: None
  ports:
    - name: http-metrics
      port: {{ .Values.ports.http }}
      targetPort: http-metrics
    - name: telemetry
      port: {{ .Values.ports.telemerty }}
      targetPort: telemetry