apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-configmap
data:
  roles.yml: |-
    admin:
      cluster:
      - all
      indices:
      - names: '*'
        privileges:
        - all
  users_roles: |-
    admin:{{ .Values.global.username }}
  users: |-
    {{ .Values.global.username }}:$2a$10$rJB8uIS8lQL0z1QCDNUDyeqCCl3Ir2zmhvoeFeJvOXeIR0SEgi7Gy