version: "3"
services:
  jaeger:
    image: "jaegertracing/all-in-one:1.51"
    container_name: jaeger
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:14269" ]
      interval: 5s
      timeout: 10s
      retries: 5
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - SPAN_STORAGE_TYPE=memory
    ports:
      - "16686:16686"
      - "14269:14269"
      - "4318:4318"
