services:
  keycloak:
    image: "bitnami/keycloak:26"
    container_name: keycloak
    environment:
      KEYCLOAK_HTTP_PORT: 8100
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_DATABASE_VENDOR: postgresql
      KEYCLOAK_DATABASE_HOST: postgres
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_USER: program
      KEYCLOAK_DATABASE_PASSWORD: "test"
      KEYCLOAK_ENABLE_HEALTH_ENDPOINTS: true
      KEYCLOAK_EXTRA_ARGS: "-Dkeycloak.profile.feature.scripts=enabled"
    ports:
      - "8100:8100"
    healthcheck:
      test: [ "CMD", "curl", "--silent", "--fail", "http://localhost:9000/health/ready" ]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - keycloak:/bitnami/keycloak
      - ./docker/keycloak/:/docker-entrypoint-initdb.d/
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  keycloak:
