---
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  strategy: allInOne
  allInOne:
    options:
      query:
        base-path: /

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    pathType: Prefix
    hosts:
      - jaeger.local

  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://elastic:9200
        username: logging
        password: qwerty
