apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-configmap
    app.kubernetes.io/version: "{{ .Values.service.image.version }}"
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: micro-services
    app.kubernetes.io/managed-by: helm
data:
  filebeat.yml: |-
    monitoring.enabled: false
    filebeat.inputs:
      - type: log
        json:
          add_error_key: true
          keys_under_root: true
          overwrite_keys: true
        paths:
          - '/var/log/{{ .Chart.Name }}-service/*.log'
    output.logstash:
      hosts: [ 'logstash-service.logging.svc.cluster.local:{{ .Values.filebeat.logstash.port }}' ]
