apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-filebeat-configmap
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-filebeat-configmap
data:
  filebeat.yml: |-
    monitoring.enabled: false
    filebeat.inputs:
      - type: log
        json:
          add_error_key: true
          keys_under_root: true
          overwrite_keys: true
        paths:
          - '/var/log/{{ .Chart.Name }}-service/*.log'
    output.logstash:
      hosts: [ 'logstash-service.logging.svc.cluster.local:{{ .Values.filebeat.logstash.port }}' ]
