apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: micro-services
    app.kubernetes.io/managed-by: helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "{{ .Values.service.metrics.path }}"
        prometheus.io/port: "{{ .Values.service.port }}"
      labels:
        app: {{ .Chart.Name }}
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/version: "{{ .Chart.Version }}"
        app.kubernetes.io/component: application
        app.kubernetes.io/part-of: micro-services
        app.kubernetes.io/managed-by: helm
    spec:
      containers:
        - name: {{ .Chart.Name }}
          imagePullPolicy: Always
          image: {{ .Values.service.image.name }}:{{ .Values.service.image.version }}

          resources:
            requests:
              memory: "{{ .Values.service.resources.requests.memory }}"
              cpu: "{{ .Values.service.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.service.resources.limits.memory }}"
              cpu: "{{ .Values.service.resources.limits.cpu }}"

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "{{ .Values.service.profile }}"
            {{ if .Values.service.database.name }}
            - name: DATABASE_NAME
              value: "{{ .Values.service.database.name }}"
            {{- end }}
            - name: DATABASE_HOST
              value: "{{ .Values.service.database.host }}"
            - name: DATABASE_PORT
              value: "{{ .Values.service.database.port }}"
            - name: DATABASE_USER
              value: "{{ .Values.service.database.username }}"
            - name: DATABAES_PASSWORD
              value: "{{ .Values.service.database.password }}"
            - name: CIRCUIT_BREAKER_ENABLED
              value: "{{ .Values.service.circuit_breaker.enabled }}"
            - name: JAEGER_ENABLED
              value: "{{ .Values.service.tracing.enabled }}"
            {{ if .Values.service.tracing.host }}
            - name: JAEGER_HOST
              value: "{{ .Values.service.tracing.host }}"
            {{- end }}
            {{ if .Values.service.tracing.port }}
            - name: JAEGER_PORT
              value: "{{ .Values.service.tracing.port }}"
          {{- end }}

          livenessProbe:
            initialDelaySeconds: 60
            failureThreshold: 10
            periodSeconds: 10
            httpGet:
              path: /manage/health/liveness
              port: {{ .Values.service.port }}
          readinessProbe:
            initialDelaySeconds: 60
            failureThreshold: 10
            periodSeconds: 10
            httpGet:
              path: /manage/health/readiness
              port: {{ .Values.service.port }}

          ports:
            - name: web
              containerPort: {{ .Values.service.port }}

          volumeMounts:
            - name: {{ .Chart.Name }}-logs-volume
              mountPath: "/var/log/{{ .Chart.Name }}-service/"

        - name: {{ .Chart.Name }}-filebeat-sidecar
          image: "docker.elastic.co/beats/filebeat:{{ .Values.filebeat.version }}"

          resources:
            requests:
              memory: "{{ .Values.filebeat.resources.requests.memory }}"
              cpu: "{{ .Values.filebeat.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.filebeat.resources.limits.memory }}"
              cpu: "{{ .Values.filebeat.resources.limits.cpu }}"

          volumeMounts:
            - name: {{ .Chart.Name }}-logs-volume
              mountPath: "/var/log/{{ .Chart.Name }}-service/"
            - name: {{ .Chart.Name }}-config-volume
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml

      volumes:
        - name: {{ .Chart.Name }}-logs-volume
        - name: {{ .Chart.Name }}-config-volume
          configMap:
            name: {{ .Chart.Name }}-configmap
            defaultMode: 420
