apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    version: 1
    editable: true

  - name: InfluxDB
    type: influxdb
    url: http://influxdb:8086
    database: k6
    access: proxy
    jsonData:
      httpMode: GET
    version: 1
    editable: true