domain: romanow-alex.ru
service:
  port: 8080
  profile: k8s
  image:
    name:
    version:
  database:
    name:
    host: postgres-service
    port: 5432
    username: program
    password: test
  circuit-breaker:
    enabled: true
  tracing:
    enabled: true
    host: jaeger-agent-service.tracing.svc.cluster.local
    port: 6831
  resources:
    requests:
      cpu: 500m
      memory: 1024Mi
    limits:
      cpu: 500m
      memory: 1024Mi
  metrics:
    path: "/manage/prometheus"
    username: management
    password: passwd

filebeat:
  version: 7.15.0
  logstash:
    port: 5044
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 50m
      memory: 128Mi