service:
  port: 8080
  profile: k8s
  image:
    name:
    version:
  resources:
    requests:
      cpu: 100m
      memory: 768Mi
    limits:
      cpu: 100m
      memory: 1024Mi
  metrics:
    path: "/manage/prometheus"
    username: management
    password: passwd

filebeat:
  version: 7.15.0
  logstash:
    port: 5044
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 50m
      memory: 128Mi