apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config-map
  labels:
    app.kubernetes.io/name: prometheus-config-map
data:
  prometheus.yml: |-
  {{- .Files.Get "config/prometheus.yml" | nindent 4 }}