apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-configmap
data:
  prometheus.yml: |-
  {{- .Files.Get "config/prometheus.yml" | nindent 4 }}