apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/version: "{{ .Values.version }}"
        app.kubernetes.io/component: monitoring
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "prom/prometheus:{{ .Values.version }}"
          args:
            - "--storage.tsdb.retention.time=12h"
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          volumeMounts:
            - name: {{ .Chart.Name }}-config-volume
              mountPath: /etc/prometheus/
            - name: {{ .Chart.Name }}-storage-volume
              mountPath: /prometheus/
      volumes:
        - name: {{ .Chart.Name }}-storage-volume
        - name: {{ .Chart.Name }}-config-volume
          configMap:
            defaultMode: 420
            name: {{ .Chart.Name }}-configmap