apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ingress-service
  labels:
    app.kubernetes.io/name: prometheus-ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  defaultBackend:
    service:
      name: prometheus-service
      port:
        number: 9090
  rules:
    - host: prometheus.romanow-alex.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-service
                port:
                  number: 9090