version: 7.15.0
port: 5044

elasticsearch:
  url: http://elasticsearch-service.elastic.svc.cluster.local:9200
  username: logging
  password: qwerty

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 100m
    memory: 768Mi