apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector-service
  labels:
    app.kubernetes.io/name: jaeger-collector-service
spec:
  selector:
    app.kubernetes.io/name: jaeger
  ports:
    - name: grpc
      port: 14250
      protocol: TCP
      targetPort: grpc
    - name: http
      port: 14268
      protocol: TCP
      targetPort: http
    - name: admin
      port: 14269
      targetPort: admin
---
# Source: jaeger/templates/query-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  labels:
    helm.sh/chart: jaeger-0.50.0
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/version: "1.22.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: query
spec:
  ports:
    - name: query
      port: 80
      protocol: TCP
      targetPort: query
    - name: admin
      port: 16687
      protocol: TCP
      targetPort: admin
  selector:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/component: query
---
# Source: jaeger/templates/agent-ds.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: jaeger-agent
  labels:
    helm.sh/chart: jaeger-0.50.0
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/version: "1.22.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: agent
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/instance: jaeger
      app.kubernetes.io/component: agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jaeger
        app.kubernetes.io/instance: jaeger
        app.kubernetes.io/component: agent
    spec:
      serviceAccountName: jaeger-agent
      containers:
        - name: jaeger-agent
          image: jaegertracing/jaeger-agent:1.22.0
          env:
            - name: REPORTER_GRPC_HOST_PORT
              value: jaeger-collector:14250
          ports:
            - name: zipkin-compact
              containerPort: 5775
              protocol: UDP
            - name: jaeger-compact
              containerPort: 6831
              protocol: UDP
            - name: jaeger-binary
              containerPort: 6832
              protocol: UDP
            - name: http
              containerPort: 5778
              protocol: TCP
            - name: admin
              containerPort: 14271
              protocol: TCP
---
# Source: jaeger/templates/collector-deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-collector
  labels:
    helm.sh/chart: jaeger-0.50.0
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/version: "1.22.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/instance: jaeger
      app.kubernetes.io/component: collector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jaeger
        app.kubernetes.io/instance: jaeger
        app.kubernetes.io/component: collector
    spec:
      containers:
        - name: jaeger-collector
          image: jaegertracing/jaeger-collector:1.22.0
          env:
            - name: SPAN_STORAGE_TYPE
              value: elasticsearch
            - name: ES_SERVER_URLS
              value: http://localhost:9300
            - name: ES_USERNAME
              value: user
            - name: ES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jaeger-elasticsearch
                  key: password
          ports:
            - containerPort: 14250
              name: grpc
              protocol: TCP
            - containerPort: 14268
              name: http
              protocol: TCP
            - containerPort: 14269
              name: admin
              protocol: TCP
---
# Source: jaeger/templates/query-deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-query
  labels:
    helm.sh/chart: jaeger-0.50.0
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/version: "1.22.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: query
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/instance: jaeger
      app.kubernetes.io/component: query
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jaeger
        app.kubernetes.io/instance: jaeger
        app.kubernetes.io/component: query
    spec:
      containers:
        - name: jaeger-query
          image: jaegertracing/jaeger-query:1.22.0
          env:
            - name: SPAN_STORAGE_TYPE
              value: elasticsearch
            - name: ES_SERVER_URLS
              value: http://localhost:9300
            - name: ES_USERNAME
              value: user
            - name: ES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jaeger-elasticsearch
                  key: password
            - name: JAEGER_AGENT_PORT
              value: "6831"
          ports:
            - name: query
              containerPort: 16686
              protocol: TCP
            - name: admin
              containerPort: 16687
              protocol: TCP
        - name: jaeger-agent-sidecar
          image: jaegertracing/jaeger-agent:1.22.0
          imagePullPolicy: IfNotPresent
          env:
            - name: REPORTER_GRPC_HOST_PORT
              value: jaeger-collector:14250
          ports:
            - name: admin
              containerPort: 14271
              protocol: TCP