global:
  name: consul
  datacenter: dc1

syncCatalog:
  enabled: true
  toK8S: true
  toConsul: true

client:
  exposeGossipPorts: true

server:
  replicas: 1
  exposeGossipAndRPCPorts: true

ui:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - host: consul.romanow-alex.ru
    annotations: |
      kubernetes.io/ingress.class: nginx

connectInject:
  enabled: true
  default: true
  namespaceSelector: |
    matchLabels:
      connect-inject : enabled

controller:
  enabled: true
