version: 7.15.0
port: 5601

elasticsearch:
  url: http://elasticsearch-service.elastic.svc.cluster.local:9200
  username: logging
  password: qwerty

resources:
  requests:
    cpu: 300m
    memory: 1024Mi
  limits:
    cpu: 500m
    memory: 1024Mi