spring.datasource.url=jdbc:postgresql://ec2-79-125-64-18.eu-west-1.compute.amazonaws.com/d87pgkjqgin8vc
spring.datasource.username=aietntdlkwihua
spring.datasource.password=4507f680dc3bb892ab05498f224a71563661d83c510e7f00ee694ce38736bbc8
spring.datasource.driver-class-name=org.postgresql.Driver