spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: ${AUTH0_CLIENT_ID:pXrawhpoDM63b82A7fkiLvRIH81wgmH9}
            client-secret: ${AUTH0_CLIENT_SECRET:LzQSxUOE2dmAUdgstWke4ngXUeZNLVczvSid7ZVV8HTegCRbOxchQtJ_23EuZ9_V}
        provider:
          auth0:
            issuer-uri: ${AUTH0_ISSUER_URI:https://romanowalex.eu.auth0.com/}
