server:
  port: ${APPLICATION_PORT:8180}

spring:
  profiles:
    active: local
    include: common
  config:
    import: optional:git.properties
  application.name: warranty
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:https://romanowalex.eu.auth0.com/}
