server:
  port: 8180

spring:
  profiles:
    active: local
    include: common
  application.name: warranty-service
  main.banner-mode: off
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://romanowalex.eu.auth0.com/