spring:
  datasource:
    url: jdbc:postgresql://postgres-service:5432/warranty
    username: program
    password: test
    driver-class-name: org.postgresql.Driver

opentracing:
  jaeger:
    enabled: true
    udp-sender:
      host: jaeger-agent-service.tracing.svc.cluster.local
      port: 6831