spring.datasource.url=jdbc:postgresql://ec2-52-214-38-135.eu-west-1.compute.amazonaws.com/d9dvsqqg94r6ep
spring.datasource.username=yykixllrgkpvsj
spring.datasource.password=2599166bc8c2d8fbc39ff1f7717c15e0b0ef3a52378359015959965b26119b3a
spring.datasource.driver-class-name=org.postgresql.Driver

warranty.service.url=https://warranty-service-app.herokuapp.com