spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/warehouse
    username: program
    password: test
    driver-class-name: org.postgresql.Driver

services:
  warranty-url: http://localhost:8180

oauth2:
  security:
    enabled: false

management:
  tracing:
    enabled: false
