spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:postgres}:${DATABASE_PORT:5432}/${DATABASE_NAME:warehouse}
    username: ${DATABASE_USER:program}
    password: ${DATABAES_PASSWORD:test}
    driver-class-name: org.postgresql.Driver

services:
  warranty-url: ${WARRANTY_URL:http://warranty-service:8180}