server:
  port: ${APPLICATION_PORT:8280}

spring:
  profiles:
    active: local
    include: common
  application.name: warehouse
  main.banner-mode: off
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:https://romanowalex.eu.auth0.com/}
