spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/orders
    username: program
    password: test
    driver-class-name: org.postgresql.Driver

services:
  warranty-url: http://warranty-service:8180
  warehouse-url: http://warehouse-service:8280