spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:postgres-service}:${DATABASE_PORT:5432}/${DATABASE_NAME:orders}
    username: ${DATABASE_USER:program}
    password: ${DATABASE_PASSWORD:test}
    driver-class-name: org.postgresql.Driver

services:
  warehouse-url: ${WAREHOUSE_URL:http://warehouse:8280}
  warranty-url: ${WARRANTY_URL:http://warranty:8180}

opentracing:
  jaeger:
    enabled: ${JAEGER_ENABLED:true}
    udp-sender:
      host: ${JAEGER_HOST:jaeger-agent}
      port: ${JAEGER_PORT:6831}
