kind: Service
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-service
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.port }}"
spec:
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
  ports:
    - name: {{ .Chart.Name }}
      protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}