apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-datasource-config-map
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-datasource-config-map
data:
  prometheus.yaml: |-
  {{- .Files.Get "config/datasource-config.yaml" | nindent 4 }}