apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-config-map
  labels:
    app.kubernetes.io/name: grafana-datasource-config-map
data:
  prometheus.yaml: |-
  {{- .Files.Get "config/datasource-config.yaml" | nindent 4 }}