kind: Service
apiVersion: v1
metadata:
  name: grafana-service
  labels:
    app.kubernetes.io/name: grafana-service
spec:
  selector:
    app.kubernetes.io/name: grafana
  ports:
    - name: grafana
      protocol: TCP
      port: 3000
      targetPort: 3000