global:
  scrape_interval: 5s
  external_labels:
    monitor: "services-monitor"

scrape_configs:
  - job_name: "services"
    metrics_path: "/manage/prometheus"
    static_configs:
      - targets:
          - "store:8480"
          - "orders:8380"
          - "warehouse:8280"
          - "warranty:8180"

  - job_name: cadvisor
    static_configs:
      - targets: [ "cadvisor:8080" ]

  - job_name: node-exporter
    static_configs:
      - targets: [ "node-exporter:9100" ]
