global:
  scrape_interval: 5s
  external_labels:
    monitor: 'services-monitor'

scrape_configs:
  - job_name: 'Order Service'
    metrics_path: '/manage/prometheus'
    basic_auth:
      username: management
      password: 'passwd'
    static_configs:
      - targets:
          - store-service:8480
          - order-service:8380
          - warehouse-service:8280
          - warranty-service:8180