global:
  scrape_interval: 5s
  external_labels:
    monitor: 'services-monitor'

scrape_configs:
  - job_name: 'Order Service'
    metrics_path: '/manage/prometheus'
    basic_auth:
      username: management
      password: 'passwd'
    static_configs:
      - targets: ['order-service:8380']

  - job_name: 'Store Service'
    metrics_path: '/manage/prometheus'
    basic_auth:
      username: management
      password: 'passwd'
    static_configs:
      - targets: ['store-service:8480']

  - job_name: 'Warehouse Service'
    metrics_path: '/manage/prometheus'
    basic_auth:
      username: management
      password: 'passwd'
    static_configs:
      - targets: ['warehouse-service:8280']

  - job_name: 'Warranty Service'
    metrics_path: '/manage/prometheus'
    basic_auth:
      username: management
      password: 'passwd'
    static_configs:
      - targets: ['warranty-service:8180']