namespace: tracing

jaeger:
  version: 1.22.0
  collector:
    resources:
      requests:
        cpu: 300m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1024Mi
    ports:
      grpc: 14250
      http: 14268
      admin: 14269

  query:
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1024Mi
    ports:
      query: 16686
      admin: 16687

  agent:
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 256Mi
    ports:
      thrift_compact: 6831
      thrift_binary: 6832
      admin: 14271

  elasticsearch:
    url: http://elasticsearch-service.elastic.svc.cluster.local:9200
    username: logging
    password: qwerty