namespace: tracing

jaeger:
  version: 1.22.0
  collector:
    ports:
      grpc: 14250
      http: 14268
      admin: 14269
  query:
    ports:
      query: 16686
      admin: 16687
  agent:
    ports:
      thrift_compact: 6831
      thrift_binary: 6832
      admin: 14271
  elasticsearch:
    url: http://elasticsearch-service.elastic.svc.cluster.local:9200
    username: logging
    password: qwerty