apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
  template:
    metadata:
      name: {{ .Chart.Name }}
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/version: "{{ .Values.version }}"
        app.kubernetes.io/component: logging
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "docker.elastic.co/kibana/kibana:{{ .Values.version }}"
          env:
            - name: ELASTICSEARCH_HOSTS
              value: http://elasticsearch-service:9200
          ports:
            - name: {{ .Chart.Name }}
              containerPort: {{ .Values.port }}