apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-deployment
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/component: logging
    app.kubernetes.io/part-of: micro-services
    app.kubernetes.io/managed-by: helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      name: {{ .Chart.Name }}
      labels:
        app: {{ .Chart.Name }}
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/version: "{{ .Chart.Version }}"
        app.kubernetes.io/component: logging
        app.kubernetes.io/part-of: micro-services
        app.kubernetes.io/managed-by: helm
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: {{ .Chart.Name }}
          image: "docker.elastic.co/kibana/kibana:{{ .Values.version }}"
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          env:
            - name: ELASTICSEARCH_HOSTS
              value: {{ .Values.elasticsearch.url }}
            - name: ELASTICSEARCH_USERNAME
              value: "{{ .Values.elasticsearch.username }}"
            - name: ELASTICSEARCH_PASSWORD
              value: "{{ .Values.elasticsearch.password }}"
          ports:
            - name: {{ .Chart.Name }}
              containerPort: {{ .Values.port }}