apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-ingress-service
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/component: logging
    app.kubernetes.io/part-of: micro-services
    app.kubernetes.io/managed-by: helm
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  defaultBackend:
    service:
      name: {{ .Chart.Name }}-service
      port:
        number: {{ .Values.port }}
  rules:
    - host: {{ .Chart.Name }}.romanow-alex.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}-service
                port:
                  number: {{ .Values.port }}