CREATE SCHEMA IF NOT EXISTS store;
GRANT USAGE ON SCHEMA store TO program;

CREATE SCHEMA IF NOT EXISTS orders;
GRANT USAGE ON SCHEMA orders TO program;

CREATE SCHEMA IF NOT EXISTS warehouse;
GRANT USAGE ON SCHEMA warehouse TO program;

CREATE SCHEMA IF NOT EXISTS warranty;
GRANT USAGE ON SCHEMA warranty TO program;