services:
  order-url: ${ORDER_URL:http://orders:8380}
  warehouse-url: ${WAREHOUSE_URL:http://warehouse:8280}
  warranty-url: ${WARRANTY_URL:http://warranty:8180}

management:
  otlp:
    tracing:
      endpoint: http://jaeger:4318/v1/traces

logging:
  pattern:
    correlation: "[%X{traceId:-},%X{spanId:-}]"
