services:
  order-url: ${ORDER_URL:http://order-service:8380}
  warehouse-url: ${WAREHOUSE_URL:http://warehouse-service:8280}
  warranty-url: ${WARRANTY_URL:http://warranty-service:8180}

opentracing:
  jaeger:
    enabled: ${JAEGER_ENABLED:true}
    udp-sender:
      host: ${JAEGER_HOST:jaeger-agent-service.tracing.svc.cluster.local}
      port: ${JAEGER_PORT:6831}