spring.datasource.url=jdbc:postgresql://localhost:5432/services
spring.jpa.properties.hibernate.default_schema=store
spring.datasource.username=program
spring.datasource.password=test
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.schemas=store

warranty.service.url=http://localhost:8180
warehouse.service.url=http://localhost:8280
order.service.url=http://localhost:8380

spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.service-registry.auto-registration.enabled=true

spring.zipkin.base-url=http://localhost:9411
spring.zipkin.discovery-client-enabled=false
spring.zipkin.locator.discovery.enabled=false

logging.graylog.enabled=true
logging.graylog.host=localhost
logging.graylog.port=12201