services:
  warranty-url: http://localhost:8180
  warehouse-url: http://localhost:8280
  order-url: http://localhost:8380

oauth2:
  security:
    enabled: false

management:
  tracing:
    enabled: false
