name: Deploy Keycloak
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log Level'
jobs:
  build:
    name: Deploy Keycloak
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_email: romanowalex@mail.ru
          appdir: docker/keycloak
          usedocker: true
          delay: 30