name: Build project
on: [ push ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build project
        uses: eskatos/gradle-command-action@v1
        with:
          dependencies-cache-enabled: true
          arguments: clean build

      - name: Deploy Store Service
        uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: store-service-app
          heroku_email: romanowalex@mail.ru
          usedocker: true
          appdir: store-service
          healthcheck: https://management:passwd@store-service-app.herokuapp.com/manage/health
          delay: 20

      - name: Deploy Warranty Service
        uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: warranty-service-app
          heroku_email: romanowalex@mail.ru
          usedocker: true
          appdir: warranty-service
          healthcheck: https://management:passwd@warranty-service-app.herokuapp.com/manage/health
          delay: 20

      - name: Deploy Warehouse Service
        uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: warehouse-service-app
          heroku_email: romanowalex@mail.ru
          usedocker: true
          appdir: warehouse-service
          healthcheck: https://management:passwd@warehouse-service-app.herokuapp.com/manage/health
          delay: 20

      - name: Deploy Order Service
        uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: order-service-app
          heroku_email: romanowalex@mail.ru
          usedocker: true
          appdir: order-service
          healthcheck: https://management:passwd@order-service-app.herokuapp.com/manage/health
          delay: 20

      - name: Stop Warehouse and Warranty service
        run: |
          heroku maintenance:on --app=warehouse-service-app
          heroku maintenance:on --app=warranty-service-app

      - name: Run API Tests
        uses: anthonyvscode/newman-action@v1
        with:
          collection: postman/postman-collection.json
          environment: postman/postman-heroku-environment.json
          delayRequest: 50
          reporters: cli

      - name: Run Warehouse and Warranty service
        if: always()
        run: |
          heroku maintenance:off --app=warehouse-service-app
          heroku maintenance:off --app=warranty-service-app

      - name: Run API Tests
        uses: anthonyvscode/newman-action@v1
        if: always()
        with:
          collection: postman/postman-collection.json
          environment: postman/postman-heroku-environment.json
          delayRequest: 50
          reporters: cli
