name: Build project
on: [ push ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_email: romanowalex@mail.ru
          appdir: docker/keycloak
          usedocker: true
          delay: 30

      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build project
        uses: eskatos/gradle-command-action@v1
        with:
          dependencies-cache-enabled: true
          arguments: clean build

      - name: Deploy Store Service
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: store-service-app
          heroku_email: romanowalex@mail.ru
          appdir: store-service
          usedocker: true
          healthcheck: https://store-service-app.herokuapp.com/manage/health
          delay: 20

      - name: Deploy Warranty Service
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: warranty-service-app
          heroku_email: romanowalex@mail.ru
          appdir: warranty-service
          usedocker: true
          healthcheck: https://warranty-service-app.herokuapp.com/manage/health
          delay: 20

      - name: Deploy Warehouse Service
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: warehouse-service-app
          heroku_email: romanowalex@mail.ru
          appdir: warehouse-service
          usedocker: true
          healthcheck: https://warehouse-service-app.herokuapp.com/manage/health
          delay: 20

      - name: Deploy Order Service
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: order-service-app
          heroku_email: romanowalex@mail.ru
          appdir: order-service
          usedocker: true
          healthcheck: https://order-service-app.herokuapp.com/manage/health
          delay: 20

      - name: Run API Tests
        id: run-newman
        uses: anthonyvscode/newman-action@v1
        with:
          collection: postman/postman-collection.json
          environment: postman/postman-heroku-environment.json
          delayRequest: 50
          reporters: cli
