apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-configmap
    app.kubernetes.io/version: "{{ .Values.version }}"
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: micro-services
    app.kubernetes.io/managed-by: helm
data:
  10-create-user-and-dbs.sql: |
    {{- range $user := .Values.users }}
    CREATE ROLE {{ $user.name }} WITH PASSWORD '{{ $user.password }}';
    ALTER ROLE {{ $user.name }} WITH LOGIN;
    {{- end }}

    {{- range $database := .Values.datases }}
    CREATE DATABASE {{ $database.name }};
    GRANT ALL PRIVILEGES ON DATABASE {{ $database.name }} TO {{ $database.user }};
    {{- end }}